### ISSUE TITLE
Order By is not working

### ISSUE THREAD

**Issue by BhavikThummar** [Fidetro/SwiftFFDB#2]
Thanks for wonderfull library. but I'm facing one issue.
I'm Trying to sort data using order by but it's not working.

let arrData = DownloadList.select(where: "downloadStatusRawValue = 0", orderBy: "priority", orderByType: .desc)

Can you please check and let me know what's wrong in it.
- Thanks

**Comment by Fidetro** [comment]
is bug,and i fix it.https://github.com/Fidetro/Swift-FFDB/commit/eb1dd55c9b439913cc406eff56063b458a6136fd
now,you can:
```
pod 'SwiftFFDB', '~> 2.0.1.2'
```
