### ISSUE TITLE
您好,我想使用事务功能,但发现FFDBTransaction 的权限不是public,所以使用不了

### ISSUE THREAD

**Issue by h912545437** [Fidetro/SwiftFFDB#3]
您好,我想使用事务功能,但发现FFDBTransaction 的权限不是public,所以使用不了

**Comment by Fidetro** [comment]
今天晚点我看一下这个问题，有问题的话会尽量这周内修复

**Comment by h912545437** [comment]
<img width="707" alt="WX20200529-165304@2x" src="https://user-images.githubusercontent.com/10666197/83241410-5edb0100-a1cd-11ea-9784-4fec4bfb88e4.png">
FFDBManager 文件里面增删改查方法里面传递进来的db没有使用,导致 SafeOperation or Transaction 不能使用

**Comment by Fidetro** [comment]
已经修复了 #4 
`pod 'SwiftFFDB', '~> 2.0.1.4'`
